// Common components index file for easier imports
export { default as Badge } from './Badge';
export { default as Button } from './Button';
export { default as Card } from './Card';
export { default as EmotionAnalyzer } from './EmotionAnalyzer';
export { default as Input } from './Input';
export { default as Navbar } from './Navbar';
export { default as ProgressBar } from './ProgressBar';
export { default as TextInput } from './TextInput';
export { default as WebcamCapture } from './WebcamCapture';